apiVersion: v1
kind: ReplicationController
metadata:
  name: consul
spec:
  replicas: 2
  selector:
    app: consul
  template:
    metadata:
      name: consul
      labels:
        app: consul
      namespace: default
    spec:
      containers:
        - name: consul
          image: danielsomerfield/consul
          ports:
            - containerPort: 8300
            - containerPort: 8301
            - containerPort: 8302
            - containerPort: 8400
            - containerPort: 8500
            - containerPort: 8600
          env:
          - name: BOOTSTRAP_EXPECT_COUNT
            value: "2"
          # TODO: ADVERTISE_HOST

    #TODO: Add volumes for persistent storage