apiVersion: v1
kind: ReplicationController
metadata:
  name: consul.2
spec:
  replicas: 1
  selector:
    app: consul
  template:
    metadata:
      name: consul_2
      labels:
        app: consul
      namespace: default
    spec:
      containers:
        - name: consul
          command: ["consul", "agent", "-server", "-bootstrap-expect=2", "-config-dir", "/consul/config",  "-data-dir", "/consul/data"]
          image: consul
          ports:
            - containerPort: 8300
            - containerPort: 8301
            - containerPort: 8302
            - containerPort: 8400
            - containerPort: 8500
            - containerPort: 8600

    #TODO: Add volumes for persistent storage