apiVersion: v1
kind: Pod
metadata:
  name: vault-consul
  namespace: default
spec:
  replicas: 2
  containers:
    - name: consul
      image: danielsomerfield/consul
      ports:
        - containerPort: 8300
        - containerPort: 8301
        - containerPort: 8302
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600
      env:
      - name: BOOTSTRAP_EXPECT_COUNT
        value: "2"
      - name: EXTERNAL_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP

#TODO: Add volumes for persistent storage